/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Conexion;
import clases.mtoCajaRegistradora;
import clases.mtoPresupuesto;
import clases.verificaciones;
import java.awt.Color;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.table.TableColumnModel;
import javax.swing.table.JTableHeader;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class PCajaVirtual extends javax.swing.JPanel {

    /**
     * Creates new form PCajaVirtual
     */
    verificaciones verificar = new verificaciones();
    DefaultComboBoxModel modeloComboPro;
    DefaultComboBoxModel modeloComboCat;
    DefaultTableModel modeloTablaProductos;
    DefaultComboBoxModel modeloComboCliente;
    DefaultComboBoxModel modeloComboPedidos;
    
    Integer codigoEmpleado=1;
    String correo;
    public static final Color greenD = new Color(217,179,16);
    public PCajaVirtual(int codigoE, String nombre) {
//        try {
//			
//                     UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//		}
//		catch (Exception e) {
//		}
        codigoEmpleado=codigoE;
        modeloTablaProductos = new DefaultTableModel(null, getColumnasProductos());
        modeloComboPro = new DefaultComboBoxModel(new String[]{});
        modeloComboCat = new DefaultComboBoxModel(new String[]{});
        modeloComboCliente = new DefaultComboBoxModel(new String[]{});
        modeloComboPedidos = new DefaultComboBoxModel(new String[]{});
        initComponents();
        
        lblCodigo.setText(String.valueOf(codigoE));
        lblNombre.setText(nombre);
        correo=nombre;
        lblOpciones.setVisible(false);
        rdFactura.setVisible(false);
        rdCredito.setVisible(false);
        cmbProducto.setEnabled(false);
        jTFCodigo.setEditable(false);
        jTFCodigoP.setEditable(false);
        jTFPrecio.setEditable(false);
        jTFStock.setEditable(false);
        try {
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
       
        llenaComboBoxClientes();
        llenaComboBoxCategoria();
       lblNombre.setText(nombre);
        ImageIcon foto0 = new ImageIcon (getClass().getResource("/images/help.png"));
       ImageIcon icono0 = new ImageIcon(foto0.getImage().getScaledInstance(25,25,Image.SCALE_DEFAULT));
       lblhelp.setIcon(icono0);
       jTFSubTotal.setVisible(false);
       lblSub.setVisible(false);
       
       jTable1.getTableHeader().setOpaque(false);
        JTableHeader header = jTable1.getTableHeader();
        
        header.setBackground(greenD);
        header.setForeground(Color.WHITE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblOpciones = new javax.swing.JLabel();
        rdFactura = new javax.swing.JRadioButton();
        rdCredito = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFCodigoP = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTFPrecio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblSub = new javax.swing.JLabel();
        jTFSubTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTFTotal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblhelp = new javax.swing.JLabel();
        cmbPedido = new javax.swing.JComboBox<>();
        cmbProducto = new javax.swing.JComboBox<>();
        NuevaVenta = new javax.swing.JRadioButton();
        Pedido = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTFStock = new javax.swing.JTextField();

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(680, 500));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 57, 42));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 196, 124), 3));
        jPanel1.setMaximumSize(new java.awt.Dimension(680, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("201524");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Empleado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Steven Diaz");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Codigo cliente:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 85, -1, 20));

        jTFCodigo.setBackground(new java.awt.Color(204, 204, 204));
        jTFCodigo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTFCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoActionPerformed(evt);
            }
        });
        jTFCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 80, 70, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cliente:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 30));

        lblOpciones.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lblOpciones.setText("Seleccione una  opcion:");
        jPanel1.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        rdFactura.setBackground(new java.awt.Color(102, 102, 102));
        rdFactura.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rdFactura.setForeground(new java.awt.Color(204, 204, 204));
        rdFactura.setText("Factura");
        rdFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(rdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        rdCredito.setBackground(new java.awt.Color(102, 102, 102));
        rdCredito.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rdCredito.setForeground(new java.awt.Color(204, 204, 204));
        rdCredito.setText("Credito Fiscal");
        jPanel1.add(rdCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pedido:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, 20));

        cmbCliente.setBackground(new java.awt.Color(51, 51, 51));
        cmbCliente.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cmbCliente.setForeground(new java.awt.Color(51, 51, 51));
        cmbCliente.setModel(modeloComboCliente);
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 150, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(60, 196, 124));
        jLabel13.setText("CAJA REGISTRADORA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Codigo Producto:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jTFCodigoP.setBackground(new java.awt.Color(204, 204, 204));
        jTFCodigoP.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTFCodigoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCodigoPKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 83, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Categoria:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTable1.setModel(modeloTablaProductos);
        jTable1.setGridColor(new java.awt.Color(0, 153, 51));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 51));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 620, 127));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Precio:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jTFPrecio.setBackground(new java.awt.Color(204, 204, 204));
        jTFPrecio.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTFPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPrecioActionPerformed(evt);
            }
        });
        jTFPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(jTFPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 83, 30));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cantidad:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jTFCantidad.setBackground(new java.awt.Color(204, 204, 204));
        jTFCantidad.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 97, 30));

        btnAgregar.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images expo/plus.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, 40));

        btnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images expo/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 100, 40));

        lblSub.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblSub.setForeground(new java.awt.Color(255, 255, 255));
        lblSub.setText("Sub-Total:");
        jPanel1.add(lblSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jTFSubTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTFSubTotal.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTFSubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSubTotalKeyTyped(evt);
            }
        });
        jPanel1.add(jTFSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 88, 30));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jTFTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTFTotal.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTFTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFTotalKeyTyped(evt);
            }
        });
        jPanel1.add(jTFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 87, 30));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images expo/continue.png"))); // NOI18N
        jButton3.setText("Continuar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 100, 40));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(217, 179, 16));
        jLabel22.setText("Detalle de venta");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 30));

        lblhelp.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblhelpAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhelpMouseClicked(evt);
            }
        });
        jPanel1.add(lblhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 25, 25));

        cmbPedido.setBackground(new java.awt.Color(51, 51, 51));
        cmbPedido.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cmbPedido.setForeground(new java.awt.Color(51, 51, 51));
        cmbPedido.setModel(modeloComboPedidos);
        cmbPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 120, 30));

        cmbProducto.setBackground(new java.awt.Color(51, 51, 51));
        cmbProducto.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cmbProducto.setForeground(new java.awt.Color(51, 51, 51));
        cmbProducto.setModel(modeloComboPro);
        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 150, 30));

        NuevaVenta.setBackground(new java.awt.Color(102, 102, 102));
        NuevaVenta.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        NuevaVenta.setForeground(new java.awt.Color(204, 204, 204));
        NuevaVenta.setText("Nueva Venta");
        NuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaVentaActionPerformed(evt);
            }
        });
        jPanel1.add(NuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        Pedido.setBackground(new java.awt.Color(102, 102, 102));
        Pedido.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Pedido.setForeground(new java.awt.Color(204, 204, 204));
        Pedido.setText("Pedido");
        Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoActionPerformed(evt);
            }
        });
        jPanel1.add(Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Venta por:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 30));

        cmbCategoria.setModel(modeloComboCat);
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, 30));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Stock:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 40, -1));

        jTFStock.setBackground(new java.awt.Color(204, 204, 204));
        jTFStock.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel1.add(jTFStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 70, 30));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private String[] getColumnasProductos() {
        String columnas[] = new String[]{"#","CODIGO", "NOMBRE", "CATEGORIA","$ UNIT.","CANTIDAD","SUBTOTAL"};
        return columnas;
    }
    Integer codCliente=1;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        

        Object envio [][] = new Object[2][modeloTablaProductos.getRowCount()];
        if (modeloTablaProductos.getRowCount()!=0) {
           System.out.println("# row: "+modeloTablaProductos.getRowCount());
                for (int i = 0;modeloTablaProductos.getRowCount() > i ; i++) {
                    envio[0][i] =modeloTablaProductos.getValueAt(i, (1));
                    envio[1][i] =modeloTablaProductos.getValueAt(i, (5));
                }
        
        
        Pago1 pago = new Pago1(String.valueOf(cmbCliente.getSelectedItem()),codigoEmpleado,Double.valueOf(jTFTotal.getText()),envio,correo,modeloTablaProductos.getRowCount());
        pago.show();  
        }else{
            JOptionPane.showMessageDialog(this,"Ingrese un producto al detalle de venta para continuar");
        }
               
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton3MouseExited

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        btnEliminar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        btnEliminar.setContentAreaFilled(true);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        // TODO add your handling code here:
        btnAgregar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        // TODO add your handling code here:
        btnAgregar.setContentAreaFilled(true);
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void jTFPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecioActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
        if (Pedido.isSelected()) {
            llenaComboBoxPedidos(String.valueOf(cmbCliente.getSelectedItem()));
        }
        
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void rdFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFacturaActionPerformed

    private void jTFCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        this.hide();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jTFCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoKeyTyped
        // TODO add your handling code here:
         char vchar = evt.getKeyChar();
        
        if (verificar.vnumeros(vchar) == true
                && (jTFCodigoP.getText().length() < 6)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCodigoKeyTyped
    private void llenaComboBoxPedidos(String correo) {
        modeloComboPedidos.removeAllElements();
        try {
                Conexion con = new Conexion();
            /* Realizamos la consulta a la base de datos*/
            String sql2="SELECT idCliente FROM cliente WHERE correoElectronico='"+correo+"'";
            PreparedStatement verDatos2 = con.conectar().prepareStatement(sql2);
            ResultSet ver2 = verDatos2.executeQuery();
            
            if(ver2.next()) {
                System.out.println("Correo: "+ver2.getInt(1));
                String sql = "SELECT idPedido FROM pedido WHERE idCliente="+ver2.getInt(1);
                jTFCodigo.setText(""+ver2.getInt(1));
                PreparedStatement verDatos = con.conectar().prepareStatement(sql);
                ResultSet ver = verDatos.executeQuery();
                while (ver.next()) {
                    
                    modeloComboPedidos.addElement(ver.getObject("idPedido"));
                }
            }else{
                modeloComboPedidos.addElement("");
            }   

        } catch (SQLException ex) {
            System.out.println("Error: " + ex);

        }
    }
 
    private void llenaComboBoxCategoria() {
        modeloComboCat.removeAllElements();
        try {
                Conexion con = new Conexion();
            /* Realizamos la consulta a la base de datos*/
            String sql2="SELECT idCategoria, nombreCategoria FROM categoriaProducto ";
            PreparedStatement verDatos2 = con.conectar().prepareStatement(sql2);
            ResultSet ver2 = verDatos2.executeQuery();
            
            while(ver2.next()){
                modeloComboCat.addElement(ver2.getObject("nombreCategoria"));
            }

        } catch (SQLException ex) {
            System.out.println("Error: " + ex);

        }
    }
    
    
    private void llenaComboBoxClientes() {
        modeloComboCliente.removeAllElements();
        try {
                Conexion con = new Conexion();
            /* Realizamos la consulta a la base de datos*/
            String sql = "SELECT correoElectronico FROM cliente";
            PreparedStatement verDatos = con.conectar().prepareStatement(sql);
            ResultSet ver = verDatos.executeQuery();
            while (ver.next()) {

                modeloComboCliente.addElement(ver.getObject("correoElectronico"));
            }

        } catch (SQLException ex) {
            System.out.println("Error: " + ex);

        }
    }    
    
    private void llenaComboBoxProductos() {
        modeloComboPro.removeAllElements();
        
        try {
            Conexion con = new Conexion();
            /* Realizamos la consulta a la base de datos*/
            String sql = "select idProductos from inventario  group by idProductos ";
            PreparedStatement verDatos = con.conectar().prepareStatement(sql);
            ResultSet ver = verDatos.executeQuery();
            while (ver.next()) {
                String sql2 = "select nombreProducto ,(SELECT top 1 stock from inventario where idProductos="+ver.getObject("idProductos")+" order by idInventario DESC) as stock FROM producto " 
                               +" WHERE idProducto= "+ver.getObject("idProductos")+"  AND idCategoria="+idCat;
                PreparedStatement verDatos2 = con.conectar().prepareStatement(sql2);
                ResultSet ver2 = verDatos2.executeQuery();
                if (ver2.next()) {
                    if(ver2.getInt("stock")!=0){
                        modeloComboPro.addElement(ver2.getString(1));
                    }
                }
            }

        } catch (SQLException ex) {
            System.out.println("Error: " + ex);
        }
    }
    private void jTFCodigoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoPKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        
        if (verificar.vnumeros(vchar) == true
                && (jTFCodigoP.getText().length() < 6)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCodigoPKeyTyped

    private void jTFPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPrecioKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        
//        if (verificar.vprecio(vchar) == true
//                && (jTextField3.getText().length() < 40)) {
//
//        } else {
//            evt.consume();
//        }
    }//GEN-LAST:event_jTFPrecioKeyTyped

    private void jTFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        
        if (verificar.vnumeros(vchar) == true
                && (jTFCantidad.getText().length() < 5)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCantidadKeyTyped

    private void jTFSubTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSubTotalKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        
        if (verificar.vprecio(vchar) == true
                && (jTFSubTotal.getText().length() < 6)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFSubTotalKeyTyped

    private void jTFTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTotalKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        
        if (verificar.vprecio(vchar) == true
                && (jTFTotal.getText().length() < 6)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFTotalKeyTyped

    private void lblhelpAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblhelpAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhelpAncestorAdded

    private void lblhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhelpMouseClicked
        // TODO add your handling code here:
        //y cuando llames el formulario ayuda en vez del 0 le vas a poner el form que le corresponda 1 2 o 3 y asi sucesivamente, si vos elegis el orden
        /**
        * ahorita, llena los textos de ayuda de todos los forms, luego vemos lo de las imagenes , me avisas cuando temrines de escribir las instrucciones
        */
        help form = new help(2);
        form.show();
    }//GEN-LAST:event_lblhelpMouseClicked
    double SubTotal=0, Total=0;
    int indices=0;
    private void cmbPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPedidoActionPerformed
        // TODO add your handling code here:
        Total = 0;
        jTFTotal.setText(String.valueOf((Total)));
        double data=0.0;
        Object datos[] = new Object[7];
        int filas = modeloTablaProductos.getRowCount();
        for (int i = 0; filas > i; i++) {
            modeloTablaProductos.removeRow(0);
        }
        try {
            Conexion cn = new Conexion();
            String sql = "SELECT dp.idProducto , pro.nombreProducto , cat.nombreCategoria, cantidadProducto "
                    + " FROM pedido p, detallePedido dp, producto pro, categoriaProducto cat "
                    + " WHERE dp.idProducto=pro.idProducto  AND cat.idCategoria=pro.idCategoria "
                    + " AND p.idPedido=dp.idPedido AND dp.idPedido=" + cmbPedido.getSelectedItem();
            PreparedStatement cmd = cn.conectar().prepareStatement(sql);
            ResultSet ver = cmd.executeQuery();
            while (ver.next()) {
                for (int i = 0; i < 5; i++) {
                    System.out.println("i: " + i);
                    if (i == 1 || i == 2 || i == 3) {
                        datos[i] = ver.getObject(i);
                    }
                    if (i == 0) {
                        datos[i] = indices;
                        indices++;
                    }
                    if (i == 4) {
                        System.out.println("Entra");
                        String sql2 = "SELECT ((((porcentajeGanacia+impuestos)/100)*precioCompra)+precioCompra) "
                                + " FROM inventario "
                                + " WHERE idProductos= " + datos[1] + " ORDER BY porcentajeGanacia DESC ";
                        PreparedStatement cmd2 = cn.conectar().prepareStatement(sql2);
                        ResultSet ver2 = cmd2.executeQuery();
                        if (ver2.next()) {
                            
                            datos[i] = ver2.getDouble(1);
                            datos[i + 1] = ver.getObject(4);
                            data = Double.valueOf(String.valueOf((datos[i + 1]))) * Double.valueOf(String.valueOf((datos[i])));
                            Total = Total + data;
                            jTFTotal.setText(String.valueOf(df.format(Total)));
                            datos[i + 2] = df.format(data);
                        }
                    }
                }
                if(validarStock(Integer.valueOf(String.valueOf(datos[1])))){
                    modeloTablaProductos.addRow(datos);
                }else{
                    JOptionPane.showMessageDialog(this,"Error no hay stock disponible del siguiente producto: "+datos[2]);
                    Total = Total - data;
                    jTFTotal.setText(String.valueOf(Total));
                }
                
            }      
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_cmbPedidoActionPerformed
    Integer stockGeneral=0;
    String categoria;
    
    private boolean validarStock(int codigo){
        Conexion con = new Conexion();
        boolean valor = true;
        try {
            String sql = "select top 1 stock from inventario where idProductos=" + codigo + " order by idInventario desc";
            PreparedStatement cmd = con.conectar().prepareStatement(sql);
            ResultSet ver = cmd.executeQuery();
            if (ver.next()) {
                if (ver.getInt(1) <= 0) {
                    valor = false;
                }
            } else {
                System.out.println("error en validar stock");
            }
        } catch (Exception e) {
            System.out.println("exc: " + e);
        }
        
        return valor;
    }
    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
        // TODO add your handling code here:
        try {
            Conexion con = new Conexion();
            System.out.println("combo: "+cmbProducto.getSelectedItem());
            String sql ="SELECT idProducto, categoriaProducto.nombreCategoria  FROM producto, categoriaProducto "
                    + " WHERE nombreProducto='"+cmbProducto.getSelectedItem()+"' AND categoriaProducto.idCategoria = producto.idCategoria";
            PreparedStatement cmd = con.conectar().prepareStatement(sql);
            ResultSet ver = cmd.executeQuery();
            if (ver.next()) {
                jTFCodigoP.setText(String.valueOf(ver.getInt(1)));
                categoria=ver.getString(2);
                
            }
        } catch (Exception e) {
            System.out.println("Aqui");
            System.out.println(e.toString());
        }
        
        mtoPresupuesto obj = new mtoPresupuesto();
        String[] datos = obj.consultarProducto(jTFCodigoP.getText());
        stockGeneral= Integer.valueOf(datos[3]);
        System.out.println("stock g: "+stockGeneral);
        jTFStock.setText(""+stockGeneral);
        double precio = (Double.parseDouble(datos[1])) + (Double.parseDouble(datos[2]));
        double precio2= (Double.parseDouble(datos[0])) * (precio/100) ;
        double precio3= precio2 +(Double.parseDouble(datos[0]));
        jTFPrecio.setText(String.valueOf(precio3));
    }//GEN-LAST:event_cmbProductoActionPerformed
    Integer contador=0;
    double total=0;
    Integer[][] stockes = new Integer[2][50];
     DecimalFormat df = new DecimalFormat("#.##");
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(jTFCantidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese una cantidad porfavor");
        }else{
            if (Integer.valueOf(jTFCantidad.getText())>stockGeneral) {
            JOptionPane.showMessageDialog(this,"No se cuenta con suficiente stock de este producto");
        }else{
            if (true) {
                
            }
         int validacion=0;
            for (int i = 0; i <contador; i++) {
                if (stockes[0][i]==Integer.valueOf(jTFCodigoP.getText())) {
                    
                    validacion=1;
                }
            }
            if (validacion==1) {
                JOptionPane.showMessageDialog(this,"Ya se encuentra este producto en el detalle");
            }else{
                Object[] datos = new Object[7];
//        Object valor0 = new Object(jTFCodigoP.getText());
                datos[0] = contador;
                datos[1] = jTFCodigoP.getText();
                datos[2] = cmbProducto.getSelectedItem();
                datos[3] = categoria;
                datos[4] = jTFPrecio.getText();
                datos[5] = jTFCantidad.getText();
                double subtotal = (Double.parseDouble(jTFPrecio.getText())) * Integer.valueOf(jTFCantidad.getText());
                datos[6] = df.format(subtotal);
                modeloTablaProductos.addRow(datos);
                //0 Codigo Pro
                stockes[0][contador] = Integer.valueOf(jTFCodigoP.getText());
                System.out.println("Codigo Producto: " + stockes[0][contador]);
                //1 Stock final
                stockes[1][contador] = stockGeneral - (Integer.valueOf(jTFCantidad.getText()));
                System.out.println("Codigo Stock Final: " + stockes[1][contador]);

                contador++;
                total = total + subtotal;
                jTFTotal.setText("" + df.format(total));
                System.out.println("Contador: " + contador);
            }
        }
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoActionPerformed
        // TODO add your handling code here:
        //jTable1.removeAll();
       Pedido.setSelected(true);
        NuevaVenta.setSelected(false);
        jTFCodigo.setEnabled(false);
        cmbProducto.setEnabled(false);
        jTFPrecio.setEnabled(false);
        jTFCantidad.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        cmbPedido.setEnabled(true);
    }//GEN-LAST:event_PedidoActionPerformed
        
    private void NuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaVentaActionPerformed
        // TODO add your handling code here:
        //jTable1.removeAll();
        Pedido.setSelected(false);
        NuevaVenta.setSelected(true);
        jTFCodigo.setEnabled(true);
        cmbProducto.setEnabled(true);
        jTFPrecio.setEnabled(true);
        jTFCantidad.setEnabled(true);
        btnAgregar.setEnabled(true);
        btnEliminar.setEnabled(true);
        cmbPedido.setEnabled(false);
        int filas = modeloTablaProductos.getRowCount();
          for (int i = 0; filas > i; i++) {
            modeloTablaProductos.removeRow(0);
        }
        Total=0.0;
        jTFTotal.setText(String.valueOf(Total));
    }//GEN-LAST:event_NuevaVentaActionPerformed
    int x=-1;
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (x!=-1) {
            Integer posicion =Integer.valueOf(String.valueOf(modeloTablaProductos.getValueAt(jTable1.getSelectedRow(), (0))));
            Integer stockT =Integer.valueOf(String.valueOf(modeloTablaProductos.getValueAt(jTable1.getSelectedRow(), (5))));
            
        //0 Codigo Pro
         stockes[0][posicion]=0;
            System.out.println("Codigo Producto 2: "+stockes[0][posicion]);
        //1 Stock final
            stockes[1][posicion]= stockes[1][posicion]+(stockT) ;
            System.out.println("Codigo Stock Final 2: "+stockes[1][posicion]);
            DecimalFormat df = new DecimalFormat("#.00");
            total=total-(Double.valueOf(String.valueOf(modeloTablaProductos.getValueAt(jTable1.getSelectedRow(), (6)))));
           modeloTablaProductos.removeRow(x);
           jTFTotal.setText(""+df.format(total));
            if (jTable1.getRowCount()==0) {
                contador=0;
                total=0;
                jTFTotal.setText(""+df.format(total));
                System.out.println("Contador: "+contador);
            }
        x=-1; 
        }else{
            JOptionPane.showMessageDialog(this,"Selecciona una fila para eliminar");
        }   
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        x=jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked
    Integer idCat;
    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
        try {
            Conexion con = new Conexion();
            String sql="SELECT idCategoria FROM categoriaProducto WHERE nombreCategoria='"+cmbCategoria.getSelectedItem()+"'";
            PreparedStatement cmd = con.conectar().prepareStatement(sql);
            ResultSet ver = cmd.executeQuery();
            if (ver.next()) {
                idCat=ver.getInt(1);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        llenaComboBoxProductos();
    }//GEN-LAST:event_cmbCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NuevaVenta;
    private javax.swing.JRadioButton Pedido;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbPedido;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCodigoP;
    private javax.swing.JTextField jTFPrecio;
    private javax.swing.JTextField jTFStock;
    private javax.swing.JTextField jTFSubTotal;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblhelp;
    private javax.swing.JRadioButton rdCredito;
    private javax.swing.JRadioButton rdFactura;
    // End of variables declaration//GEN-END:variables
}
