/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Conexion;
import clases.mtoUsuarios;
import clases.verificaciones;
import java.awt.Image;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author steve
 */
public class PProveedores extends javax.swing.JPanel {

    Conexion con = new Conexion();
    DefaultTableModel modeloTablaProveedores;
    /**
     * Creates new form PProveedores
     */
    verificaciones verificar = new verificaciones();
    String correo;
    public PProveedores(String correoE) {
         modeloTablaProveedores= new DefaultTableModel(null, getColumnasProveedores());
         setFilas();
//         try {
//                     UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//		}
//		catch (Exception e) {
                
//		}
        initComponents();
        correo=correoE;
        jTextField1.setEnabled(false);
        ImageIcon foto0 = new ImageIcon (getClass().getResource("/images/help.png"));
       ImageIcon icono0 = new ImageIcon(foto0.getImage().getScaledInstance(25,25,Image.SCALE_DEFAULT));
       lblhelp.setIcon(icono0);
    }
    private String[] getColumnasProveedores() {
        String columnas[] = new String[]{"ID PROVEEDOR", "NOMBRE", "DIRECCION", "TELEFONO", "FAX", "CORREO", "ESTADO"};
        return columnas;
    }
    private void setFilas() {
        try {
            String consulta = "SELECT idProveedor, nombreProveedor, direccion, telefono, fax,correoElectronico,estado FROM proveedor";

            PreparedStatement us = con.conectar().prepareStatement(consulta);
            ResultSet res = us.executeQuery();

            Object datos[] = new Object[7];

            while (res.next()) {
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = res.getObject(i + 1);
                }
                modeloTablaProveedores.addRow(datos);
            }
            res.close();
        } catch (SQLException ex) {
            Logger.getLogger(PProveedores.class.getName()).log(Level.SEVERE,null,ex);
        }

    }
    private void setFilasP(int tipo,String valores) {
        try {
            String sql="";
            switch (tipo) {
                //Codigo Empleado
                case 1:
                    sql = "SELECT idProveedor, nombreProveedor, direccion,telefono, fax,correoElectronico,estado "
                            + "FROM proveedor WHERE idProveedor like '"+valores+"%'";
                    break;
                //Nombre
                case 2:
                    sql = "SELECT idProveedor, nombreProveedor, direccion,telefono, fax,correoElectronico,estado "
                            + "FROM proveedor WHERE nombreProveedor like '"+valores+"%'";
                    break;
                default:
                    sql = "SELECT idProveedor, nombreProveedor, direccion,telefono, fax,correoElectronico,estado "
                            + "FROM proveedor "
                            + "WHERE idProveedor>0";
                    break;
            }
            PreparedStatement us = con.conectar().prepareStatement(sql);
            ResultSet resultado = us.executeQuery();

            Object datos[] = new Object[7];

            while (resultado.next()) {
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = resultado.getObject(i + 1);
                }
                modeloTablaProveedores.addRow(datos);
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTFBuscarP = new javax.swing.JTextField();
        rdNombreP = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdCodigoP = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblhelp = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 3));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(modeloTablaProveedores);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 315, 200));

        jTFBuscarP.setBackground(new java.awt.Color(204, 204, 204));
        jTFBuscarP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFBuscarP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBuscarPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBuscarPKeyTyped(evt);
            }
        });
        add(jTFBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 110, 30));

        rdNombreP.setBackground(new java.awt.Color(102, 102, 102));
        rdNombreP.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        rdNombreP.setForeground(new java.awt.Color(255, 255, 255));
        rdNombreP.setText("Nombre");
        rdNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNombrePActionPerformed(evt);
            }
        });
        add(rdNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 63, -1, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 20));

        rdCodigoP.setBackground(new java.awt.Color(102, 102, 102));
        rdCodigoP.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        rdCodigoP.setForeground(new java.awt.Color(255, 255, 255));
        rdCodigoP.setText("Codigo");
        rdCodigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCodigoPActionPerformed(evt);
            }
        });
        add(rdCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 63, -1, 30));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 155, 30));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 106, 60, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 30));

        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Generar Reporte");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton4.setContentAreaFilled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(71, 30));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 120, -1));

        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Modificar");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton5.setContentAreaFilled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, -1));

        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Agregar");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton6.setContentAreaFilled(false);
        jButton6.setPreferredSize(new java.awt.Dimension(71, 30));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, -1));

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 155, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Direccion:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 30));

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 155, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fax:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 260, 30, 30));

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 155, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo Electronico:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 155, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Gestion de los Proveedores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 31));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        lblhelp.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblhelpAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhelpMouseClicked(evt);
            }
        });
        add(lblhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 25, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 30));

        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Limpiar");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton7.setContentAreaFilled(false);
        jButton7.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 90, -1));

        jButton8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Eliminar");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton8.setContentAreaFilled(false);
        jButton8.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.hide();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
         jButton4.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
         jButton4.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
         jButton6.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
         jButton6.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
         jButton5.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
         jButton5.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton5MouseExited

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vletras(vchar) == true
                && (jTextField3.getText().length() < 40)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        
            evt.consume();
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vnumeros(vchar) == true
                && (jTextField2.getText().length() < 8)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vletrasynumeros(vchar) == true
                && (jTextField5.getText().length() < 40)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vnumeros(vchar) == true
                && (jTextField6.getText().length() < 14)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vcorreoevent(vchar) == true
                && (jTextField7.getText().length() < 40)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTFBuscarPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarPKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vletrasynumeros(vchar) == true
                && (jTextField7.getText().length() < 30)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFBuscarPKeyTyped

    private void lblhelpAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblhelpAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_lblhelpAncestorAdded

    private void lblhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhelpMouseClicked
        // TODO add your handling code here:
        //y cuando llames el formulario ayuda en vez del 0 le vas a poner el form que le corresponda 1 2 o 3 y asi sucesivamente, si vos elegis el orden
        /**
        * ahorita, llena los textos de ayuda de todos los forms, luego vemos lo de las imagenes , me avisas cuando temrines de escribir las instrucciones
        */
        help form = new help(15);
        form.show();
    }//GEN-LAST:event_lblhelpMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        verificaciones obj = new verificaciones();      
        mtoUsuarios objeto = new mtoUsuarios();
        if(obj.vcorreo(jTextField7.getText())){
//        objeto.consultasRandom();
        if(!(jTextField3.getText().isEmpty()&&jTextField2.getText().isEmpty()
            && jTextField7.getText().isEmpty()&&jTextField6.getText().isEmpty()
            &&jTextField5.getText().isEmpty()&&jTextField1.getText().isEmpty())){
                objeto.setNombreP(String.valueOf(jTextField3.getText()));
                objeto.setTelefonoP(Integer.valueOf(jTextField2.getText()));
                objeto.setCorreoP(String.valueOf(jTextField7.getText()));
                objeto.setFaxP(Integer.valueOf(jTextField6.getText()));
                objeto.setDireccionP(String.valueOf(jTextField5.getText()));
                String texto= String.valueOf(jComboBox1.getSelectedItem());
                
            if(jTextField1.getText().isEmpty()){
                
                if (texto.equals("Activo")) {
                   objeto.setEstadoP(1);
                   if(objeto.guardarProveedor()){
                        JOptionPane.showMessageDialog(this, "Proveedor agregado");
                        
                        int filas = modeloTablaProveedores.getRowCount();
                       for (int i = 0; filas > i; i++) {
                           modeloTablaProveedores.removeRow(0);
                       }
                        setFilas();
                    }else{
                        JOptionPane.showMessageDialog(this, "Error al agregar");
                    }
                }else if (texto.equals("Inactivo")) {
                    objeto.setEstadoP(0);
                    if(objeto.guardarProveedor()){
                        JOptionPane.showMessageDialog(this, "Proveedor agregado");
                        int filas = modeloTablaProveedores.getRowCount();
                       for (int i = 0; filas > i; i++) {
                           modeloTablaProveedores.removeRow(0);
                       }
                        setFilas();
                    }else{
                        JOptionPane.showMessageDialog(this, "Error al agrgar");
                    }
                
                }else{
                        JOptionPane.showMessageDialog(this,"Seleccione un estado de el proveedor");
                    }
                
            }else{
                objeto.setIdP(Integer.valueOf(jTextField1.getText()));
                    if(objeto.checkProveedor()){
                    JOptionPane.showMessageDialog(this, "Ya existe ese usuario registrado");
                }else{
                    if (texto.equals("Activo")) {
                       objeto.setEstadoP(1);
                       if(objeto.guardarProveedor()){
                            JOptionPane.showMessageDialog(this, "Proveedor agregado");
                            int filas = modeloTablaProveedores.getRowCount();
                       for (int i = 0; filas > i; i++) {
                           modeloTablaProveedores.removeRow(0);
                       }
                            setFilas();
                        }else{
                            JOptionPane.showMessageDialog(this, "Error al agregar");
                        }
                    }else if (texto.equals("Inactivo")) {
                        objeto.setEstadoP(0);
                        if(objeto.guardarProveedor()){
                            JOptionPane.showMessageDialog(this, "Proveedor agregado");
                            int filas = modeloTablaProveedores.getRowCount();
                       for (int i = 0; filas > i; i++) {
                           modeloTablaProveedores.removeRow(0);
                       }
                            setFilas();
                        }else{
                            JOptionPane.showMessageDialog(this, "Error al agrgar");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this,"Seleccione un estado de el proveedor");
                    }
            }
            }   
          
        }else{
                JOptionPane.showMessageDialog(this,"Ingrese todos los datos");
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Ingrese un formato de correo valido");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        verificaciones obj = new verificaciones();      
        mtoUsuarios objeto = new mtoUsuarios();
        if(obj.vcorreo(jTextField7.getText())){
        objeto.setNombreP(String.valueOf(jTextField3.getText()));
        objeto.setTelefonoP(Integer.valueOf(jTextField2.getText()));
        objeto.setCorreoP(String.valueOf(jTextField7.getText()));
        objeto.setFaxP(Integer.valueOf(jTextField6.getText()));
        objeto.setDireccionP(String.valueOf(jTextField5.getText()));
        String texto= String.valueOf(jComboBox1.getSelectedItem());
        objeto.setIdP(Integer.valueOf(jTextField1.getText()));
        
            if (texto.equals("Activo")) {
               objeto.setEstadoP(1);
               if(objeto.modificarProveedor()){
                    JOptionPane.showMessageDialog(this, "Proveedor modificado");
                    int filas = modeloTablaProveedores.getRowCount();
                       for (int i = 0; filas > i; i++) {
                           modeloTablaProveedores.removeRow(0);
                       }
                       setFilas();
                }else{
                    JOptionPane.showMessageDialog(this, "Error al modificar");
                }
            }else if (texto.equals("Inactivo")) {
                objeto.setEstadoP(0);
                if(objeto.modificarProveedor()){
                    JOptionPane.showMessageDialog(this, "Proveedor modificado");
                    int filas = modeloTablaProveedores.getRowCount();
                       for (int i = 0; filas > i; i++) {
                           modeloTablaProveedores.removeRow(0);
                       }
                       setFilas();
                }else{
                    JOptionPane.showMessageDialog(this, "Error al modificar");
                }
            
        }
        }else{
            JOptionPane.showMessageDialog(this,"Ingrese un formato de correo valido");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTextField3.setText(String.valueOf(modeloTablaProveedores.getValueAt(jTable1.getSelectedRow(), (1))));
        jTextField1.setText(String.valueOf(modeloTablaProveedores.getValueAt(jTable1.getSelectedRow(), (0))));
        jTextField2.setText(String.valueOf(modeloTablaProveedores.getValueAt(jTable1.getSelectedRow(), (3))));
        jTextField5.setText(String.valueOf(modeloTablaProveedores.getValueAt(jTable1.getSelectedRow(), (2))));
        jTextField6.setText(String.valueOf(modeloTablaProveedores.getValueAt(jTable1.getSelectedRow(), (4))));
        jTextField7.setText(String.valueOf(modeloTablaProveedores.getValueAt(jTable1.getSelectedRow(), (5))));
        
        String texto = String.valueOf(modeloTablaProveedores.getValueAt(jTable1.getSelectedRow(), (6)));
        if (texto.equals("true")) {
            jComboBox1.setSelectedItem("Activo");
        }else{
            jComboBox1.setSelectedItem("Inactivo");
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTFBuscarPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarPKeyReleased
        // TODO add your handling code here:
        if (rdNombreP.isSelected()) {
            int filas = modeloTablaProveedores.getRowCount();
            for (int i = 0; filas > i; i++) {
                modeloTablaProveedores.removeRow(0);
            }
            setFilasP(2, jTFBuscarP.getText());
        } else if (rdCodigoP.isSelected()) {
            int filas = modeloTablaProveedores.getRowCount();
            for (int i = 0; filas > i; i++) {
                modeloTablaProveedores.removeRow(0);
            }
            setFilasP(1, jTFBuscarP.getText());
        }
    }//GEN-LAST:event_jTFBuscarPKeyReleased

    private void rdNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNombrePActionPerformed
        // TODO add your handling code here:
        rdCodigoP.setSelected(false);
        jTFBuscarP.setEnabled(true);
        tipo2=2;
    }//GEN-LAST:event_rdNombrePActionPerformed

    private void rdCodigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCodigoPActionPerformed
        // TODO add your handling code here:
        rdNombreP.setSelected(false);
        jTFBuscarP.setEnabled(true);
        tipo2=1;
    }//GEN-LAST:event_rdCodigoPActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        
        jTextField3.setText(null);
        
        jTextField2.setText(null);
        
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un proveedor para eliminar");
        }else{
            mtoUsuarios obj = new mtoUsuarios();
            obj.setIdP(Integer.valueOf(jTextField1.getText()));
            if (obj.eliminarProveedor()) {
                JOptionPane.showMessageDialog(this, "Proveedor eliminado");
                jTextField1.setText(null);

                jTextField3.setText(null);

                jTextField2.setText(null);

                jTextField5.setText(null);
                jTextField6.setText(null);
                jTextField7.setText(null);
                jComboBox1.setSelectedIndex(0);
            }else{
                JOptionPane.showMessageDialog(this, "Productos relacionados a este proveedor");
            }         
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
int tipo2=0;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String path ="";
        try {
            Conexion con = new Conexion();
//            //establecemos la ruta donde esta el reportes
//            path = getClass().getResource("/reportes/Secciones.jasper").getPath();
//            //se decodifica por algun caracter especial
//            path = URLDecoder.decode(path,"UTF-8");
//            System.out.println("path: "+path);
//            //Se crea la conexion
//            
//            //Se crean los parametros
//            Map parametros = new HashMap();
//            parametros.put("Nombre","Steven Diaz");
//            //Se crea el objeto reporte
//            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
//            //se crea el objeto de impresion del reporte 
//            JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,con.conectar());
//            //ahora se crea el visor, donde se muestra el reporte
//            JasperViewer visor = new JasperViewer(imprimir, false);
//            visor.setTitle("Reporte de proyectos e integrantes");
//            visor.setVisible(true);
            
            
            String archivo= getClass().getResource("/reportes/ReporteProveedores.jrxml").getPath();
            archivo = URLDecoder.decode(archivo,"UTF-8");
            JasperReport report = JasperCompileManager.compileReport(archivo);
            Map parametros = new HashMap();
                      
           parametros.put("tipo",tipo2);
           parametros.put("valores",jTFBuscarP.getText());
            try {
                String sql ="SELECT numRegistro, nombreEmpresa, domicilioLegal, fechaConstitucion, logo, telefono, correoElectronico, propietario "
                        + "FROM datosEmpresa";
                PreparedStatement cmd = con.conectar().prepareStatement(sql);
                ResultSet ver = cmd.executeQuery();
                if (ver.next()) {
                   parametros.put("#registro",ver.getInt(1));
                   parametros.put("nombreEmpresa",ver.getString(2));
                   parametros.put("domicilio",ver.getString(3));
                   parametros.put("fechaConstitucion",ver.getString(4));
                   parametros.put("imagen",ver.getString(5));
                   parametros.put("telefono",ver.getString(6));
                   parametros.put("correo",ver.getString(7));
                   parametros.put("propietario",ver.getString(8));
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            parametros.put("autor", correo); 
            JasperPrint print = JasperFillManager.fillReport(report, parametros, con.conectar());
 
            JasperViewer visor = new JasperViewer(print, false);
            visor.setTitle("Reporte de Documento de Empleados");
            visor.setVisible(true);
 
            
        } catch (JRException e) {
            System.out.println("AQUI1");
            System.out.println(e.getMessage());
            
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(PProveedores.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBuscarP;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblhelp;
    private javax.swing.JRadioButton rdCodigoP;
    private javax.swing.JRadioButton rdNombreP;
    // End of variables declaration//GEN-END:variables
}
