/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.mtoProductos;
import clases.Conexion;
import clases.verificaciones;
import java.awt.Image;
import java.io.File;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author steve
 */
public class PProductos extends javax.swing.JPanel {

    /**
     * Creates new form PProductos
     */
    verificaciones verificar = new verificaciones();
    mtoProductos productos = new mtoProductos();
    DefaultTableModel modeloTablaCategoria;
    DefaultTableModel modeloTablaProducto;
    
    DefaultComboBoxModel modeloComboCategoria;
    DefaultComboBoxModel modeloComboProveedor;
    /**
     * Variables generales
     */
    String codigoC="",nombreC="",codigoP="",correo="";
    File fichero;
    String datos=String.valueOf(fichero);
    
    public PProductos(String correoE) {
//                try {
//                     UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//		}
//		catch (Exception e) {
//		}
        initComponents();
        correo=correoE;
        ImageIcon foto0 = new ImageIcon (getClass().getResource("/images/help.png"));
       ImageIcon icono0 = new ImageIcon(foto0.getImage().getScaledInstance(25,25,Image.SCALE_DEFAULT));
       lblhelp.setIcon(icono0);
       lblhelp1.setIcon(icono0);
        
        modeloComboCategoria = new DefaultComboBoxModel(new String[]{});
        cmbCategoria.setModel(productos.llenarComboCategoria(modeloComboCategoria));
        
        modeloComboProveedor = new DefaultComboBoxModel(new String[]{});
        cmbProveedor.setModel(productos.llenarComboProveedor(modeloComboProveedor));
        
        modeloTablaCategoria = new DefaultTableModel(null, productos.getColumnasCategoria());
        jTable2.setModel(productos.setFilasCategorias(modeloTablaCategoria, 0, ""));

        modeloTablaProducto = new DefaultTableModel(null, productos.getColumnasProducto());
        jTable1.setModel(productos.setFilasProductos(modeloTablaProducto, 0, ""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblCodigoP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFNombreP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbProveedor = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTADescripcionP = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        lblhelp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCodigoC = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jTFNombreC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rdSi = new javax.swing.JRadioButton();
        rdNo = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTFBuscarC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rdCodigoC = new javax.swing.JRadioButton();
        rdNombreC = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        lblhelp1 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 3));
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigoP.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigoP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCodigoP.setForeground(new java.awt.Color(204, 204, 204));
        lblCodigoP.setText("Codigo:");
        jPanel1.add(lblCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 220, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        jTFNombreP.setBackground(new java.awt.Color(204, 204, 204));
        jTFNombreP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFNombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombrePKeyTyped(evt);
            }
        });
        jPanel1.add(jTFNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Descripcion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Buscar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 50, 20));

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 40, 90, 30));

        jRadioButton1.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Nombre");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, 30));

        jRadioButton2.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Codigo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, 30));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 80, 340, 158));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Generar Reporte");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton1.setContentAreaFilled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(113, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(113, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(113, 30));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 130, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Imagen:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Categoria:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Proveedor:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 155, 30));

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 155, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Examinar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton2.setContentAreaFilled(false);
        jButton2.setDoubleBuffered(true);
        jButton2.setPreferredSize(new java.awt.Dimension(77, 30));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 90, -1));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(204, 204, 204));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setPreferredSize(new java.awt.Dimension(71, 30));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 90, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPreferredSize(new java.awt.Dimension(75, 30));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 90, -1));

        jRadioButton7.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton7.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Categoria");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 40, -1, 30));

        jTADescripcionP.setBackground(new java.awt.Color(204, 204, 204));
        jTADescripcionP.setColumns(20);
        jTADescripcionP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTADescripcionP.setRows(5);
        jScrollPane3.setViewportView(jTADescripcionP);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 170, 140));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(204, 204, 204));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnModificar.setContentAreaFilled(false);
        btnModificar.setPreferredSize(new java.awt.Dimension(75, 30));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, -1));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 130, 130));

        lblhelp.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblhelpAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhelpMouseClicked(evt);
            }
        });
        jPanel1.add(lblhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 25, 25));

        jTabbedPane1.addTab("Gestion de Productos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigoC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCodigoC.setForeground(new java.awt.Color(204, 204, 204));
        lblCodigoC.setText("Codigo:");
        jPanel2.add(lblCodigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 30));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        jTFNombreC.setBackground(new java.awt.Color(204, 204, 204));
        jTFNombreC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFNombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreCKeyTyped(evt);
            }
        });
        jPanel2.add(jTFNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Descripcion:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Visualizacion 3D:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        rdSi.setBackground(new java.awt.Color(102, 102, 102));
        rdSi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdSi.setForeground(new java.awt.Color(255, 255, 255));
        rdSi.setText("Si");
        rdSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSiActionPerformed(evt);
            }
        });
        jPanel2.add(rdSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        rdNo.setBackground(new java.awt.Color(102, 102, 102));
        rdNo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdNo.setForeground(new java.awt.Color(255, 255, 255));
        rdNo.setText("No");
        rdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNoActionPerformed(evt);
            }
        });
        jPanel2.add(rdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 30));

        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("Eliminar");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton6.setContentAreaFilled(false);
        jButton6.setPreferredSize(new java.awt.Dimension(71, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 90, -1));

        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 72, 310, 180));

        jTFBuscarC.setBackground(new java.awt.Color(204, 204, 204));
        jTFBuscarC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFBuscarC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBuscarCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBuscarCKeyTyped(evt);
            }
        });
        jPanel2.add(jTFBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Buscar:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 26, -1, 30));

        rdCodigoC.setBackground(new java.awt.Color(102, 102, 102));
        rdCodigoC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdCodigoC.setForeground(new java.awt.Color(255, 255, 255));
        rdCodigoC.setText("Codigo");
        rdCodigoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCodigoCActionPerformed(evt);
            }
        });
        jPanel2.add(rdCodigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 30));

        rdNombreC.setBackground(new java.awt.Color(102, 102, 102));
        rdNombreC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdNombreC.setForeground(new java.awt.Color(255, 255, 255));
        rdNombreC.setText("Nombre");
        rdNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNombreCActionPerformed(evt);
            }
        });
        jPanel2.add(rdNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 30));

        jButton8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 204, 204));
        jButton8.setText("Generar Reporte");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton8.setContentAreaFilled(false);
        jButton8.setMaximumSize(new java.awt.Dimension(113, 30));
        jButton8.setMinimumSize(new java.awt.Dimension(113, 30));
        jButton8.setPreferredSize(new java.awt.Dimension(113, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 140, -1));

        jTADescripcion.setBackground(new java.awt.Color(204, 204, 204));
        jTADescripcion.setColumns(20);
        jTADescripcion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTADescripcion.setRows(5);
        jScrollPane4.setViewportView(jTADescripcion);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 150, 160));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 204, 204));
        jButton9.setText("Agregar");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton9.setContentAreaFilled(false);
        jButton9.setPreferredSize(new java.awt.Dimension(71, 30));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, -1));

        jButton10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 204, 204));
        jButton10.setText("Modificar");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton10.setContentAreaFilled(false);
        jButton10.setPreferredSize(new java.awt.Dimension(71, 30));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 90, -1));

        lblhelp1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblhelp1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblhelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhelp1MouseClicked(evt);
            }
        });
        jPanel2.add(lblhelp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 25, 25));

        jTabbedPane1.addTab("Gestion de Categorias", jPanel2);

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path ="";
        try {
            Conexion con = new Conexion();
//            //establecemos la ruta donde esta el reportes
//            path = getClass().getResource("/reportes/Secciones.jasper").getPath();
//            //se decodifica por algun caracter especial
//            path = URLDecoder.decode(path,"UTF-8");
//            System.out.println("path: "+path);
//            //Se crea la conexion
//            
//            //Se crean los parametros
//            Map parametros = new HashMap();
//            parametros.put("Nombre","Steven Diaz");
//            //Se crea el objeto reporte
//            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
//            //se crea el objeto de impresion del reporte 
//            JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,con.conectar());
//            //ahora se crea el visor, donde se muestra el reporte
//            JasperViewer visor = new JasperViewer(imprimir, false);
//            visor.setTitle("Reporte de proyectos e integrantes");
//            visor.setVisible(true);
            
            
            String archivo= getClass().getResource("/reportes/ReporteProductos.jrxml").getPath();
            archivo = URLDecoder.decode(archivo,"UTF-8");
            JasperReport report = JasperCompileManager.compileReport(archivo);
            Map parametros = new HashMap();
            int tipo=0;
            if (jRadioButton1.isSelected()) {
                tipo=2;
            }else if (jRadioButton2.isSelected()){
                tipo=1;
            }else if (jRadioButton7.isSelected()) {
                tipo=3;
            }
            parametros.put("tipo",tipo);
            parametros.put("valores",jTextField4.getText());
            
            try {
                String sql ="SELECT numRegistro, nombreEmpresa, domicilioLegal, fechaConstitucion, logo, telefono, correoElectronico, propietario "
                        + "FROM datosEmpresa";
                PreparedStatement cmd = con.conectar().prepareStatement(sql);
                ResultSet ver = cmd.executeQuery();
                if (ver.next()) {
                    System.out.println("Entra");
                   parametros.put("#registro",ver.getInt(1));
                   parametros.put("nombreEmpresa",ver.getString(2));
                   parametros.put("domicilio",ver.getString(3));
                   parametros.put("fechaConstitucion",ver.getString(4));
                   parametros.put("imagen",ver.getString(5));
                   parametros.put("telefono",ver.getString(6));
                   parametros.put("correo",ver.getString(7));
                   parametros.put("propietario",ver.getString(8));
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            parametros.put("autor", correo);
            JasperPrint print = JasperFillManager.fillReport(report, parametros, con.conectar());
 
            JasperViewer visor = new JasperViewer(print, false);
            visor.setTitle("Reporte de Productos");
            visor.setVisible(true);
 
            
        } catch (JRException e) {
            System.out.println("AQUI1");
            System.out.println(e.getMessage());
            
        } 
        catch (UnsupportedEncodingException ex) {
            System.out.println("AQUI2");
            Logger.getLogger(PInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.hide();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         String path ="";
        try {
            Conexion con = new Conexion();
//            //establecemos la ruta donde esta el reportes
//            path = getClass().getResource("/reportes/Secciones.jasper").getPath();
//            //se decodifica por algun caracter especial
//            path = URLDecoder.decode(path,"UTF-8");
//            System.out.println("path: "+path);
//            //Se crea la conexion
//            
//            //Se crean los parametros
//            Map parametros = new HashMap();
//            parametros.put("Nombre","Steven Diaz");
//            //Se crea el objeto reporte
//            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
//            //se crea el objeto de impresion del reporte 
//            JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,con.conectar());
//            //ahora se crea el visor, donde se muestra el reporte
//            JasperViewer visor = new JasperViewer(imprimir, false);
//            visor.setTitle("Reporte de proyectos e integrantes");
//            visor.setVisible(true);
            
            
            String archivo= getClass().getResource("/reportes/ReporteCategorias.jrxml").getPath();
            archivo = URLDecoder.decode(archivo,"UTF-8");
            JasperReport report = JasperCompileManager.compileReport(archivo);
            Map parametros = new HashMap();
            int tipo=0;
            if (rdCodigoC.isSelected()) {
                tipo=1;
            }else if (rdNombreC.isSelected()){
                tipo=2;
            }
            parametros.put("tipo",tipo);
            parametros.put("valores",jTFBuscarC.getText());
            
            try {
                String sql ="SELECT numRegistro, nombreEmpresa, domicilioLegal, fechaConstitucion, logo, telefono, correoElectronico, propietario "
                        + "FROM datosEmpresa";
                PreparedStatement cmd = con.conectar().prepareStatement(sql);
                ResultSet ver = cmd.executeQuery();
                if (ver.next()) {
                    System.out.println("Entra");
                   parametros.put("#registro",ver.getInt(1));
                   parametros.put("nombreEmpresa",ver.getString(2));
                   parametros.put("domicilio",ver.getString(3));
                   parametros.put("fechaConstitucion",ver.getString(4));
                   parametros.put("imagen",ver.getString(5));
                   parametros.put("telefono",ver.getString(6));
                   parametros.put("correo",ver.getString(7));
                   parametros.put("propietario",ver.getString(8));
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            parametros.put("autor", correo);
            JasperPrint print = JasperFillManager.fillReport(report, parametros, con.conectar());
 
            JasperViewer visor = new JasperViewer(print, false);
            visor.setTitle("Reporte de Categoria");
            visor.setVisible(true);
 
            
        } catch (JRException e) {
            System.out.println("AQUI1");
            System.out.println(e.getMessage());
            
        } 
        catch (UnsupportedEncodingException ex) {
            System.out.println("AQUI2");
            Logger.getLogger(PInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
         jButton1.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
         jButton1.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        // TODO add your handling code here:
         btnAgregar.setContentAreaFilled(true);
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        // TODO add your handling code here:
         btnAgregar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
         btnEliminar.setContentAreaFilled(true);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
         btnEliminar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
         jButton2.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
         jButton2.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void jTFNombrePKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombrePKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vletras(vchar) == true
                && (jTFNombreP.getText().length() < 30)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFNombrePKeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vletrasynumeros(vchar) == true
                && (jTextField4.getText().length() < 12)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTFNombreCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreCKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vletrasynumeros(vchar) == true
                && (jTFNombreC.getText().length() < 20)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFNombreCKeyTyped

    private void jTFBuscarCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarCKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
       
        if (verificar.vletrasynumeros(vchar) == true
                && (jTFBuscarC.getText().length() < 40)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTFBuscarCKeyTyped

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (jTFNombreC.getText().isEmpty() || (rdSi.isSelected()== false && rdNo.isSelected()==false)) {
            JOptionPane.showMessageDialog(this,"Error campos vacios");
        }else{
            mtoProductos obj = new mtoProductos();
            obj.setNombreC(jTFNombreC.getText());
            obj.setDescripC(jTADescripcion.getText());
            if (rdSi.isSelected()==true) {
                obj.setV3D(1);
            }else{
                obj.setV3D(2);
            }
            if (obj.guardarCategoria()) {
                JOptionPane.showMessageDialog(this,"Categoria Guardada Correctamente");
                int filas = modeloTablaCategoria.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaCategoria.removeRow(0);
                }         
                obj.setFilasCategorias(modeloTablaCategoria, 0, "");
            }else{
                JOptionPane.showMessageDialog(this,"Error al guardar categoria");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
        codigoC=String.valueOf(modeloTablaCategoria.getValueAt(jTable2.getSelectedRow(), (0)));
        lblCodigoC.setText("Codigo: "+codigoC);
        jTFNombreC.setText(String.valueOf(modeloTablaCategoria.getValueAt(jTable2.getSelectedRow(), (1))));
        jTADescripcion.setText(String.valueOf(modeloTablaCategoria.getValueAt(jTable2.getSelectedRow(), (2))));
        String V3D = String.valueOf(modeloTablaCategoria.getValueAt(jTable2.getSelectedRow(), (3)));
        if (V3D.equals("SI")) {
            rdSi.setSelected(true);
            rdNo.setSelected(false);
        }else{
            rdSi.setSelected(false);
            rdNo.setSelected(true);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (codigoC.equals("")) {
            JOptionPane.showMessageDialog(this,"Error campos vacios");
        }else{
            mtoProductos obj = new mtoProductos();
            obj.setCodigoC(Integer.valueOf(codigoC));
            if (obj.eliminarCategoria()) {
                JOptionPane.showMessageDialog(this,"Categoria Eliminada Correctamente");
                int filas = modeloTablaCategoria.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaCategoria.removeRow(0);
                }         
                obj.setFilasCategorias(modeloTablaCategoria, 0, "");
                lblCodigoC.setText("Codigo:");
                jTFNombreC.setText(null);
                jTADescripcion.setText(null);
                rdSi.setSelected(false);
                rdNo.setSelected(false);
            }else{
                JOptionPane.showMessageDialog(this,"Error al eliminar categoria");
            }
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        if (jTFNombreC.getText().isEmpty() || (rdSi.isSelected()== false && rdNo.isSelected()==false)) {
            JOptionPane.showMessageDialog(this,"Error campos vacios");
        }else{
            mtoProductos obj = new mtoProductos();
            obj.setCodigoC(Integer.valueOf(codigoC));
            obj.setNombreC(jTFNombreC.getText());
            obj.setDescripC(jTADescripcion.getText());
            if (rdSi.isSelected()==true) {
                obj.setV3D(1);
            }else{
                obj.setV3D(2);
            }
            if (obj.modificarCategoria()) {
                JOptionPane.showMessageDialog(this,"Categoria Modificada Correctamente");
                int filas = modeloTablaCategoria.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaCategoria.removeRow(0);
                }         
                obj.setFilasCategorias(modeloTablaCategoria, 0, "");
            }else{
                JOptionPane.showMessageDialog(this,"Error al modificar categoria");
            }
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void rdSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSiActionPerformed
        // TODO add your handling code here:
        rdNo.setSelected(false);
    }//GEN-LAST:event_rdSiActionPerformed

    private void rdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNoActionPerformed
        // TODO add your handling code here:
        rdSi.setSelected(false);
    }//GEN-LAST:event_rdNoActionPerformed

    private void rdCodigoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCodigoCActionPerformed
        // TODO add your handling code here:
        rdNombreC.setSelected(false);
    }//GEN-LAST:event_rdCodigoCActionPerformed

    private void rdNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNombreCActionPerformed
        // TODO add your handling code here:
        rdCodigoC.setSelected(false);
    }//GEN-LAST:event_rdNombreCActionPerformed

    private void jTFBuscarCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarCKeyReleased
        // TODO add your handling code here:
         mtoProductos obj = new mtoProductos();
        if (rdCodigoC.isSelected()==true) {
            int filas = modeloTablaCategoria.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaCategoria.removeRow(0);
                }         
                obj.setFilasCategorias(modeloTablaCategoria,  1,jTFBuscarC.getText() );
        }else if (rdNombreC.isSelected()==true) {
            int filas = modeloTablaCategoria.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaCategoria.removeRow(0);
                }         
                obj.setFilasCategorias(modeloTablaCategoria, 2,jTFBuscarC.getText() );
        }
    }//GEN-LAST:event_jTFBuscarCKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (jTFNombreP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error campos vacios");
        } else {
            mtoProductos obj = new mtoProductos();
            Conexion cn = new Conexion();
            obj.setNombreP(jTFNombreP.getText());
            obj.setImagen(String.valueOf(fichero));
            obj.setDescripP(jTADescripcionP.getText());
            try {
                String sql = "SELECT idCategoria FROM categoriaProducto WHERE nombreCategoria='" + cmbCategoria.getSelectedItem() + "'";
                PreparedStatement cmd = cn.conectar().prepareStatement(sql);
                ResultSet ver = cmd.executeQuery();
                if (ver.next()) {
                    obj.setCodigoCategoria(ver.getInt(1));
                }

                String sql2 = "SELECT idProveedor FROM proveedor WHERE nombreProveedor='" + cmbProveedor.getSelectedItem() + "'";
                PreparedStatement cmd2 = cn.conectar().prepareStatement(sql2);
                ResultSet ver2 = cmd2.executeQuery();
                if (ver2.next()) {
                    obj.setCodigoProveedor(ver2.getInt(1));
                }

            } catch (Exception e) {
                System.out.println(e.toString());
            }
            if (obj.guardarProducto()) {
                JOptionPane.showMessageDialog(this, "Producto guardado correctamente");
                //Como sacarlo
                int filas = modeloTablaProducto.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaProducto.removeRow(0);
                }
                obj.setFilasProductos(modeloTablaProducto, 0, "");


            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar producto");
            }

            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (jTFNombreP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error campos vacios");
        } else {
            mtoProductos obj = new mtoProductos();
            Conexion cn = new Conexion();
            obj.setCodigoP(Integer.valueOf(codigoP));
            obj.setNombreP(jTFNombreP.getText());
            obj.setImagen(String.valueOf(fichero));
            obj.setDescripP(jTADescripcionP.getText());
            try {
                String sql = "SELECT idCategoria FROM categoriaProducto WHERE nombreCategoria='" + cmbCategoria.getSelectedItem() + "'";
                PreparedStatement cmd = cn.conectar().prepareStatement(sql);
                ResultSet ver = cmd.executeQuery();
                if (ver.next()) {
                    obj.setCodigoCategoria(ver.getInt(1));
                }

                String sql2 = "SELECT idProveedor FROM proveedor WHERE nombreProveedor='" + cmbProveedor.getSelectedItem() + "'";
                PreparedStatement cmd2 = cn.conectar().prepareStatement(sql2);
                ResultSet ver2 = cmd2.executeQuery();
                if (ver2.next()) {
                    obj.setCodigoProveedor(ver2.getInt(1));
                }

            } catch (Exception e) {
                System.out.println(e.toString());
            }
            if (obj.modificarProducto()) {
                JOptionPane.showMessageDialog(this, "Producto modificado correctamente");
                int filas = modeloTablaProducto.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaProducto.removeRow(0);
                }
                obj.setFilasProductos(modeloTablaProducto, 0, "");

            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar producto");
            }

            
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (codigoP.equals("")) {
            JOptionPane.showMessageDialog(this,"Error, selecciona un producto para eliminar");
        }else{
            mtoProductos obj = new mtoProductos();
            obj.setCodigoP(Integer.valueOf(codigoP));
            if (obj.eliminarProducto()) {
                JOptionPane.showMessageDialog(this,"Producto eliminado correctamente");
                lblCodigoP.setText("Codigo: ");
                jTFNombreP.setText(null);
                jTADescripcionP.setText(null);
                lblFoto.setText(null);
                
                int filas = modeloTablaProducto.getRowCount();
            for (int i = 0; filas > i; i++) {
                modeloTablaProducto.removeRow(0);
            }
            obj.setFilasProductos(modeloTablaProducto, 0, "");
            }else{
                JOptionPane.showMessageDialog(this,"Error al eliminar producto");
            }
            
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int resultado;
        fileChooser ventana = new fileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("PNG","png");
        ventana.jfchCargarFoto.setFileFilter(filtro);
        resultado = ventana.jfchCargarFoto.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = ventana.jfchCargarFoto.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(fichero.toString());
                ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
                lblFoto.setIcon(icono);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen " + ex);
            }
        }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblhelpAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblhelpAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhelpAncestorAdded

    private void lblhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhelpMouseClicked
        // TODO add your handling code here:
        //y cuando llames el formulario ayuda en vez del 0 le vas a poner el form que le corresponda 1 2 o 3 y asi sucesivamente, si vos elegis el orden
        /**
        * ahorita, llena los textos de ayuda de todos los forms, luego vemos lo de las imagenes , me avisas cuando temrines de escribir las instrucciones
        */
        help form = new help(14);
        form.show();
    }//GEN-LAST:event_lblhelpMouseClicked

    private void lblhelp1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblhelp1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhelp1AncestorAdded

    private void lblhelp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhelp1MouseClicked
        // TODO add your handling code here:
        //y cuando llames el formulario ayuda en vez del 0 le vas a poner el form que le corresponda 1 2 o 3 y asi sucesivamente, si vos elegis el orden
        /**
        * ahorita, llena los textos de ayuda de todos los forms, luego vemos lo de las imagenes , me avisas cuando temrines de escribir las instrucciones
        */
        help form = new help(14);
        form.show();
    }//GEN-LAST:event_lblhelp1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        codigoP=String.valueOf(modeloTablaProducto.getValueAt(jTable1.getSelectedRow(), (0)));
        lblCodigoP.setText("Codigo: "+codigoP);
        jTFNombreP.setText(String.valueOf(modeloTablaProducto.getValueAt(jTable1.getSelectedRow(), (1))));
        jTADescripcionP.setText(String.valueOf(modeloTablaProducto.getValueAt(jTable1.getSelectedRow(), (2))));
        cmbCategoria.setSelectedItem(String.valueOf(modeloTablaProducto.getValueAt(jTable1.getSelectedRow(), (4))));
        cmbProveedor.setSelectedItem(String.valueOf(modeloTablaProducto.getValueAt(jTable1.getSelectedRow(), (3))));
        try {
            Conexion cn = new Conexion();
            String sql ="SELECT imagen FROM producto WHERE idProducto = '"+codigoP+"'";
            PreparedStatement cmd = cn.conectar().prepareStatement(sql);
            ResultSet ver = cmd.executeQuery();
            if (ver.next()) {
               ImageIcon icon = new ImageIcon(ver.getString(1));
                ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
                lblFoto.setIcon(icono);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        mtoProductos obj = new mtoProductos();
         if (jRadioButton1.isSelected()) {
            int filas = modeloTablaProducto.getRowCount();
            for (int i = 0; filas > i; i++) {
                modeloTablaProducto.removeRow(0);
            }
            obj.setFilasProductos(modeloTablaProducto,2, jTextField4.getText());
        } else if (jRadioButton2.isSelected()) {
            int filas = modeloTablaProducto.getRowCount();
            for (int i = 0; filas > i; i++) {
                modeloTablaProducto.removeRow(0);
            }
            obj.setFilasProductos(modeloTablaProducto,1, jTextField4.getText());
        }else if (jRadioButton7.isSelected()) {
            int filas = modeloTablaProducto.getRowCount();
            for (int i = 0; filas > i; i++) {
                modeloTablaProducto.removeRow(0);
            }
           obj.setFilasProductos(modeloTablaProducto, 3, jTextField4.getText());
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton7.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton7.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextArea jTADescripcionP;
    private javax.swing.JTextField jTFBuscarC;
    private javax.swing.JTextField jTFNombreC;
    private javax.swing.JTextField jTFNombreP;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblCodigoC;
    private javax.swing.JLabel lblCodigoP;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblhelp;
    private javax.swing.JLabel lblhelp1;
    private javax.swing.JRadioButton rdCodigoC;
    private javax.swing.JRadioButton rdNo;
    private javax.swing.JRadioButton rdNombreC;
    private javax.swing.JRadioButton rdSi;
    // End of variables declaration//GEN-END:variables
}
