/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import clases.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
/**
 *
 * @author steven
 */
public class PTipoUsuario extends javax.swing.JPanel {

    /** Creates new form PTipoUsuario */
    DefaultTableModel modeloTablaPrivilegios;
    Conexion cn = new Conexion();
    String CodigoPrivilegios="";
    public PTipoUsuario() {
        modeloTablaPrivilegios= new DefaultTableModel(null, getColumnasPrivilegios());setFilasPrivilegios(0);
        try {
                     UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
		}
		catch (Exception e) {
		}
        initComponents();
    }
    private String[] getColumnasPrivilegios() {
        String columnas[] = new String[]{"CODIGO"};
        return columnas;
    }

    private void setFilasPrivilegios(int datos2) {
        try {
            String sql="";
            if (datos2==0) {
                sql = "SELECT idPrivilegio FROM privilegio";
            }else{
                sql = "SELECT idPrivilegio FROM privilegio WHERE idPrivilegio="+datos2;
            }
            

            PreparedStatement us = cn.conectar().prepareStatement(sql);
            ResultSet resultado = us.executeQuery();

            Object datos[] = new Object[1];

            while (resultado.next()) {
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = resultado.getObject(i + 1);
                }
                modeloTablaPrivilegios.addRow(datos);
            }
        } catch (Exception e) {

        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCodigoTipo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTFNombreTipo = new javax.swing.JTextField();
        rdNombre = new javax.swing.JRadioButton();
        rdCodigo = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFBuscarT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbPrivilegios = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cbInventario = new javax.swing.JCheckBox();
        cbConstruirEquipo = new javax.swing.JCheckBox();
        cbProductos = new javax.swing.JCheckBox();
        cbSolicitarAyuda = new javax.swing.JCheckBox();
        cbOrdenesCola = new javax.swing.JCheckBox();
        cbCajaRegistradora = new javax.swing.JCheckBox();
        cbVentas = new javax.swing.JCheckBox();
        cbChatCenter = new javax.swing.JCheckBox();
        cbDatosEmpresa = new javax.swing.JCheckBox();
        cbGestionarVentas = new javax.swing.JCheckBox();
        cbBitacoras = new javax.swing.JCheckBox();
        cbClientes = new javax.swing.JCheckBox();
        cbProveedores = new javax.swing.JCheckBox();
        cbEmpleados = new javax.swing.JCheckBox();
        cbGestionarProductos = new javax.swing.JCheckBox();
        cbGestionarInventario = new javax.swing.JCheckBox();
        btnAgregarP = new javax.swing.JButton();
        btnEliminarP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTFBuscarT1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        btnModificarP = new javax.swing.JButton();
        lblCodigoPrivilegio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigoTipo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCodigoTipo.setForeground(new java.awt.Color(204, 204, 204));
        lblCodigoTipo.setText("CODIGO TIPO");
        jPanel2.add(lblCodigoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 260, 130));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Agregar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(71, 30));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Eliminar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton2.setContentAreaFilled(false);
        jButton2.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Buscar:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jTFNombreTipo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFNombreTipo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTFNombreTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, 30));

        rdNombre.setText("Nombre");
        jPanel2.add(rdNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 30));

        rdCodigo.setText("Codigo");
        jPanel2.add(rdCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 30));

        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("Generar Reporte");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton6.setContentAreaFilled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        jTFBuscarT.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFBuscarT.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTFBuscarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 80, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Privilegios:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Nombre Tipo:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel2.add(cmbPrivilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 30));

        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Modificar");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton5.setContentAreaFilled(false);
        jButton5.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestionar Tipos de Usuario", jPanel1);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione los privilegios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbInventario.setText("Ver Inventario");
        jPanel5.add(cbInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cbConstruirEquipo.setText("Construir Equipo");
        jPanel5.add(cbConstruirEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cbProductos.setText("Ver Productos");
        jPanel5.add(cbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cbSolicitarAyuda.setText("Solicitar Ayuda");
        jPanel5.add(cbSolicitarAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cbOrdenesCola.setText("Ver ordenes en cola");
        jPanel5.add(cbOrdenesCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        cbCajaRegistradora.setText("Gestionar Caja Virtual");
        cbCajaRegistradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCajaRegistradoraActionPerformed(evt);
            }
        });
        jPanel5.add(cbCajaRegistradora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cbVentas.setText("Ver ventas");
        jPanel5.add(cbVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cbChatCenter.setText("Chat Center");
        jPanel5.add(cbChatCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cbDatosEmpresa.setText("Cambiar Datos Empresa");
        jPanel5.add(cbDatosEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        cbGestionarVentas.setText("Gestionar Ventas");
        jPanel5.add(cbGestionarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        cbBitacoras.setText("Gestionar Bitacoras");
        jPanel5.add(cbBitacoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        cbClientes.setText("Gestionar Clientes");
        jPanel5.add(cbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        cbProveedores.setText("Gestionar Proveedores");
        jPanel5.add(cbProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        cbEmpleados.setText("Gestionar Empleados");
        jPanel5.add(cbEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        cbGestionarProductos.setText("Gestionar Productos");
        jPanel5.add(cbGestionarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        cbGestionarInventario.setText("Gestionar Inventario");
        jPanel5.add(cbGestionarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 370, 320));

        btnAgregarP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAgregarP.setForeground(new java.awt.Color(204, 204, 204));
        btnAgregarP.setText("Agregar");
        btnAgregarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnAgregarP.setContentAreaFilled(false);
        btnAgregarP.setPreferredSize(new java.awt.Dimension(71, 30));
        btnAgregarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarPMouseExited(evt);
            }
        });
        jPanel4.add(btnAgregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        btnEliminarP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnEliminarP.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminarP.setText("Eliminar");
        btnEliminarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEliminarP.setContentAreaFilled(false);
        btnEliminarP.setPreferredSize(new java.awt.Dimension(75, 30));
        btnEliminarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarPMouseExited(evt);
            }
        });
        jPanel4.add(btnEliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jTable2.setModel(modeloTablaPrivilegios);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 260, 150));

        jTFBuscarT1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFBuscarT1.setForeground(new java.awt.Color(204, 204, 204));
        jTFBuscarT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBuscarT1KeyReleased(evt);
            }
        });
        jPanel4.add(jTFBuscarT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 80, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Buscar:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 204, 204));
        jButton7.setText("Generar Reporte");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton7.setContentAreaFilled(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, 30));

        btnModificarP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnModificarP.setForeground(new java.awt.Color(204, 204, 204));
        btnModificarP.setText("Modificar");
        btnModificarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnModificarP.setContentAreaFilled(false);
        btnModificarP.setPreferredSize(new java.awt.Dimension(75, 30));
        btnModificarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarPMouseExited(evt);
            }
        });
        jPanel4.add(btnModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        lblCodigoPrivilegio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCodigoPrivilegio.setForeground(new java.awt.Color(204, 204, 204));
        lblCodigoPrivilegio.setText("CODIGO PRIVILEGIO");
        jPanel4.add(lblCodigoPrivilegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jTabbedPane1.addTab("Gestionar Privilegios", jPanel4);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.hide();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
         jButton6.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
         jButton6.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
         jButton1.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
         jButton1.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
         jButton2.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
         jButton2.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void btnAgregarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPMouseEntered

    private void btnAgregarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPMouseExited

    private void btnEliminarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPMouseEntered

    private void btnEliminarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPMouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseExited

    private void btnModificarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPMouseEntered

    private void btnModificarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPMouseExited

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        CodigoPrivilegios=String.valueOf(modeloTablaPrivilegios.getValueAt(jTable2.getSelectedRow(), 0));
        lblCodigoPrivilegio.setText("CODIGO PRIVILEGIO: "+CodigoPrivilegios);
        mtoTipoUsuarios objeto = new mtoTipoUsuarios();
        objeto.setCodigoP(Integer.valueOf(CodigoPrivilegios));
        Boolean[] valores = objeto.consultarPrivilegio();
        //Integer[] valores2 = new Integer[jPanel5.getComponentCount()];
        for (int x = 0; x < jPanel5.getComponentCount(); x++) {
            if (jPanel5.getComponent(x) instanceof JCheckBox) {
                JCheckBox check = (JCheckBox) jPanel5.getComponent(x);
                check.setSelected(valores[x]);
            }
        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void btnAgregarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPMouseClicked
        // TODO add your handling code here:
        //Eliminar y volver a agregar todos los checkbox en orde de base de datos o hacer algo parecido ORDEN!
        Integer[] valores= new Integer[jPanel5.getComponentCount()];
        for(int x=0;x<jPanel5.getComponentCount();x++){
                if(jPanel5.getComponent(x) instanceof JCheckBox){
                    JCheckBox check=(JCheckBox) jPanel5.getComponent(x);
                  if(check.isSelected()){
                       //System.out.println(check.getText());
                       valores[x]=1;
                   }else{
                      valores[x]=0;
                  }
                }
            }
        mtoTipoUsuarios objeto = new mtoTipoUsuarios();
        if (objeto.guardarPrivilegio(valores)) {
            JOptionPane.showMessageDialog(this,"Privilegio guardado correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Error al guardar datos");
        }
        int filas = modeloTablaPrivilegios.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaPrivilegios.removeRow(0);
                }
                setFilasPrivilegios(0);
        
    }//GEN-LAST:event_btnAgregarPMouseClicked

    private void cbCajaRegistradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCajaRegistradoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCajaRegistradoraActionPerformed

    private void btnModificarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPMouseClicked
        // TODO add your handling code here:
        Integer[] valores= new Integer[jPanel5.getComponentCount()];
        for(int x=0;x<jPanel5.getComponentCount();x++){
            
                if(jPanel5.getComponent(x) instanceof JCheckBox){
                    JCheckBox check=(JCheckBox) jPanel5.getComponent(x);
                  if(check.isSelected()){
                       //System.out.println(check.getText());
                       valores[x]=1;
                   }else{
                      valores[x]=0;
                  }
                }     
       }
        mtoTipoUsuarios objeto = new mtoTipoUsuarios();
        if (objeto.modificarPrivilegio(valores,Integer.valueOf(CodigoPrivilegios))) {
            JOptionPane.showMessageDialog(this,"Privilegio modificado correctamente");
        }else{
            JOptionPane.showMessageDialog(this,"Error al modificar datos");
        }
        int filas = modeloTablaPrivilegios.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modeloTablaPrivilegios.removeRow(0);
                }
                setFilasPrivilegios(0);
        
    }//GEN-LAST:event_btnModificarPMouseClicked

    private void btnEliminarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar este privilegio?", "Confirmacion",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION || response==JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(this,"Privilegio no eliminado");
        }else{
            if (lblCodigoPrivilegio.getText().equals("CODIGO PRIVILEGIO")) {
                JOptionPane.showMessageDialog(this, "No ha seleccionado ningun privilegio para eliminar");
            } else {
                mtoTipoUsuarios objeto = new mtoTipoUsuarios();
                objeto.setCodigoP(Integer.valueOf(CodigoPrivilegios));
                if (objeto.eliminarPrivilegio()) {
                    JOptionPane.showMessageDialog(this, "Privilegio eliminado correctamente");
                    lblCodigoPrivilegio.setText("CODIGO PRIVILEGIO");    
                    int filas = modeloTablaPrivilegios.getRowCount();
                    for (int i = 0; filas > i; i++) {
                        modeloTablaPrivilegios.removeRow(0);
                    }
                    setFilasPrivilegios(0);
                    for (int x = 0; x < jPanel5.getComponentCount(); x++) {
                        if (jPanel5.getComponent(x) instanceof JCheckBox) {
                            JCheckBox check = (JCheckBox) jPanel5.getComponent(x);
                            if (check.isSelected()) {
                                check.setSelected(false);
                            }      
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error existen tipos de usuario relacionados a este Privilegio. \n Elimina o modifica antes a los tipo usuarios relacionados para poder eliminar este privilegio.");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarPMouseClicked

    private void jTFBuscarT1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarT1KeyReleased
        // TODO add your handling code here:
        try{
          int filas = modeloTablaPrivilegios.getRowCount();
        for (int i = 0; filas > i; i++) {
            modeloTablaPrivilegios.removeRow(0);
        }
        setFilasPrivilegios(Integer.valueOf(jTFBuscarT1.getText()));  
        }catch(Exception e){
            int filas = modeloTablaPrivilegios.getRowCount();
        for (int i = 0; filas > i; i++) {
            modeloTablaPrivilegios.removeRow(0);
        }
        setFilasPrivilegios(0);  
        }    
    }//GEN-LAST:event_jTFBuscarT1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnModificarP;
    private javax.swing.JCheckBox cbBitacoras;
    private javax.swing.JCheckBox cbCajaRegistradora;
    private javax.swing.JCheckBox cbChatCenter;
    private javax.swing.JCheckBox cbClientes;
    private javax.swing.JCheckBox cbConstruirEquipo;
    private javax.swing.JCheckBox cbDatosEmpresa;
    private javax.swing.JCheckBox cbEmpleados;
    private javax.swing.JCheckBox cbGestionarInventario;
    private javax.swing.JCheckBox cbGestionarProductos;
    private javax.swing.JCheckBox cbGestionarVentas;
    private javax.swing.JCheckBox cbInventario;
    private javax.swing.JCheckBox cbOrdenesCola;
    private javax.swing.JCheckBox cbProductos;
    private javax.swing.JCheckBox cbProveedores;
    private javax.swing.JCheckBox cbSolicitarAyuda;
    private javax.swing.JCheckBox cbVentas;
    private javax.swing.JComboBox<String> cmbPrivilegios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFBuscarT;
    private javax.swing.JTextField jTFBuscarT1;
    private javax.swing.JTextField jTFNombreTipo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCodigoPrivilegio;
    private javax.swing.JLabel lblCodigoTipo;
    private javax.swing.JRadioButton rdCodigo;
    private javax.swing.JRadioButton rdNombre;
    // End of variables declaration//GEN-END:variables

}
